-- CREATE DATABASE empresa;

-- USE empresa;

-- CREATE TABLE empleados (
--   id int(4) NOT NULL AUTO_INCREMENT PRIMARY KEY,
--   name varchar(30), NOT NULL,
--   contractTypeName varchar(30), NOT NULL,
--   roleId varchar(30), NOT NULL,
--   roleDescripcion varchar(300), NOT NULL,
--   hourlySalary int(40),
--   monthlySalary int(40),
--   numberDocument int(30) NOT NULL,
--   fechaNacimiento date NOT NULL,
--   direccion varchar(40,  NOT NULL,
--   ciudad varchar(40), NOT NULL,
--   estadoCivil varchar(20), NOT NULL,
--   numeroCelular int(11) NOT NULL,
--   numeroFijo int(11),
-- fechaIngreso date NOT NULL,
--   tipoDocumento int(30) NOT NULL,
--   barrio varchar(30) NOT NULL,
--   estado varchar(20) NOT NULL
--   create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
